version: '3.7'
services:
  traefik:
    secrets:
      - traefik_users
  backend:
    secrets:
      - BACKEND_SECRETS
      - SOCIAL_PROVIDER_SECRETS
      - POSTGRES_PASSWORD
  frontend:
    secrets:
      - FRONTEND_SECRETS
      - SOCIAL_PROVIDER_SECRETS
  celery_worker:
    secrets:
      - BACKEND_SECRETS
      - SOCIAL_PROVIDER_SECRETS
      - POSTGRES_PASSWORD
  postgres:
    secrets:
      - POSTGRES_PASSWORD

secrets:
  traefik_users:
    file: ../traefik_users
  BACKEND_SECRETS:
    file: ../backend.secrets
  FRONTEND_SECRETS:
    file: ../frontend.secrets
  SOCIAL_PROVIDER_SECRETS:
    file: ../social-provider.secrets
  POSTGRES_PASSWORD:
    file: ../postgres.secrets
