version: '3.7'
services:
  traefik:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - postgres_backups:/backups
volumes:
  postgres_data:
  postgres_backups:
