version: '3.7'
services:
  backend:
    volumes:
      - ../postgres.secrets:/POSTGRES_PASSWORD
      - ../backend.secrets:/BACKEND_SECRETS
      - ../social-provider.secrets:/SOCIAL_PROVIDER_SECRETS
      - ../backend:/app
  frontend:
    volumes:
      - ../frontend:/app
      - ../frontend.secrets:/FRONTEND_SECRETS
      - ../social-provider.secrets:/SOCIAL_PROVIDER_SECRETS
      - frontend_node_modules:/app/node_modules
  celery_worker:
    volumes:
      - ../postgres.secrets:/POSTGRES_PASSWORD
      - ../backend.secrets:/BACKEND_SECRETS
      - ../social-provider.secrets:/SOCIAL_PROVIDER_SECRETS
      - ../backend:/app
  postgres:
    volumes:
      - ../postgres.secrets:/POSTGRES_PASSWORD

volumes:
  frontend_node_modules:
