# Generated by Django 2.2.5 on 2019-10-20 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school", models.TextField(max_length=200, verbose_name="Escola")),
                (
                    "year",
                    models.TextField(
                        choices=[
                            ("EF7", "7º do Fundamental"),
                            ("EF8", "8º do Fundamental"),
                            ("EF9", "9º do Fundamental"),
                            ("EM1", "1º do Médio"),
                            ("EM2", "2º do Médio"),
                            ("EM3", "3º do Médio"),
                        ],
                        max_length=3,
                        verbose_name="Série",
                    ),
                ),
                (
                    "student_proof_url",
                    models.URLField(verbose_name="URL do atestado de matrícula"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.TextField(max_length=20, verbose_name="Telefone")),
                ("cpf", models.TextField(max_length=14, verbose_name="CPF")),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.Student",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=200, verbose_name="Nome")),
                ("phone", models.TextField(max_length=20, verbose_name="Telefone")),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.Student",
                    ),
                ),
            ],
        ),
    ]
