# Generated by Django 2.2.5 on 2019-10-20 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birthday", models.DateField(verbose_name="Data de aniversário")),
                (
                    "gender",
                    models.TextField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Feminino"),
                            ("O", "Outro"),
                            ("NA", "Prefiro não dizer"),
                        ],
                        max_length=2,
                        verbose_name="Gênero",
                    ),
                ),
                ("phone", models.TextField(max_length=20, verbose_name="Telefone")),
                ("cep", models.TextField(max_length=9, verbose_name="CEP")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Documentation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rg", models.TextField(max_length=20, verbose_name="RG")),
                ("rgIssueDate", models.DateField(verbose_name="Data de emissão do RG")),
                (
                    "rgIssuer",
                    models.TextField(max_length=30, verbose_name="Órgão emissor do RG"),
                ),
                (
                    "rgState",
                    models.TextField(
                        max_length=2, verbose_name="Estado de emissão do RG"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
